# Generated by Django 3.0 on 2020-01-14 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_app', '0012_activity_polymorphic_ctype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityQuiz',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course_app.Activity')),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('course_app.activity',),
        ),
    ]
