# Generated by Django 3.0 on 2020-01-21 04:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('activity_quiz', '0003_activityquiz_max_attempts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singlechoiceanswer',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='question',
            name='shuffle',
            field=models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], default=False),
        ),
        migrations.RemoveField(
            model_name='singlechoiceanswer',
            name='id',
        ),
        migrations.AddField(
            model_name='singlechoiceanswer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='singlechoiceanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_set', to='activity_quiz.SingleChoiceQuestion'),
        ),
    ]
