# Generated by Django 3.0 on 2020-01-21 06:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0015_auto_20200117_0303'),
        ('activity_quiz', '0007_openquestion_placeholder'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionQuiz',
            fields=[
                ('solution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course_app.Solution')),
                ('attempt', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('answers', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('course_app.solution',),
        ),
    ]
