# Generated by Django 3.0 on 2020-01-23 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_quiz', '0009_activityquiz_timelimit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutionquiz',
            name='started_at',
        ),
    ]
