# Generated by Django 3.0 on 2020-01-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_quiz', '0010_remove_solutionquiz_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityquiz',
            name='congratulations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
