# Generated by Django 3.0 on 2020-02-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_quiz', '0011_activityquiz_congratulations'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityquiz',
            name='confirmation_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
