# Generated by Django 3.0 on 2020-02-11 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_quiz', '0012_activityquiz_confirmation_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderinQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_quiz.Question')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('activity_quiz.question',),
        ),
    ]
