# Generated by Django 3.0 on 2020-02-11 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('activity_quiz', '0013_orderinquestion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderinQuestion',
            new_name='OrderingQuestion',
        ),
    ]
