# Generated by Django 3.0 on 2020-02-12 00:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('activity_quiz', '0014_auto_20200211_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderingAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('gap_pos', models.IntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_set', to='activity_quiz.OrderingQuestion')),
            ],
        ),
    ]
