# Generated by Django 3.0 on 2020-02-12 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_quiz', '0015_orderinganswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinganswer',
            name='gap_pos',
        ),
        migrations.AlterField(
            model_name='orderinganswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distractors', to='activity_quiz.OrderingQuestion'),
        ),
    ]
