# Generated by Django 3.0 on 2020-01-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_note', '0002_auto_20200114_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitynote',
            name='completable',
            field=models.BooleanField(default=False),
        ),
    ]
