# Generated by Django 3.0 on 2020-01-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_note', '0003_activitynote_completable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitynote',
            name='completable',
            field=models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], default=False),
        ),
    ]
