# Generated by Django 3.0 on 2020-01-14 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_note', '0005_auto_20200114_0524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noteactivity',
            options={'base_manager_name': 'objects'},
        ),
    ]
