# Generated by Django 3.0 on 2020-01-14 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0012_activity_polymorphic_ctype'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('activity_note', '0007_remove_noteactivity_completable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NoteActivity',
            new_name='ActivityNote',
        ),
    ]
