# Generated by Django 3.0 on 2020-01-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_note', '0008_auto_20200114_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitynote',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
