# Generated by Django 3.0 on 2020-01-17 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0014_solution'),
        ('activity_note', '0011_notesolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionNote',
            fields=[
                ('solution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course_app.Solution')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('course_app.solution',),
        ),
        migrations.DeleteModel(
            name='NoteSolution',
        ),
    ]
