# Generated by Django 3.0 on 2020-02-07 06:38

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_user_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('icon_class', models.TextField(help_text='Font-awesome icon css class (e.g <em>fas fa-alien-monster</em>)', validators=[django.core.validators.RegexValidator(code='invalid_icon_class', message='Invalid font-awesom icon class', regex='^(fas|far|fal|fab|fad|) fa-\\w+$')])),
                ('color', models.CharField(default='ffffff', help_text='Background color in format: <em>DDDDDD</em> (e.g. 00ff00)', max_length=6, validators=[django.core.validators.RegexValidator(code='invalid_color', message='Provide color as six hexadecimal digits.', regex='^[0-9a-f]{6}$')])),
            ],
        ),
    ]
