# Generated by Django 3.0 on 2020-02-07 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_auto_20200207_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='achievements',
            field=models.ManyToManyField(through='user_app.AcquiredAchievement', to='user_app.Achievement'),
        ),
        migrations.AlterField(
            model_name='acquiredachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.Achievement'),
        ),
        migrations.AlterField(
            model_name='acquiredachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
