# Generated by Django 3.0 on 2020-03-08 12:54
import logging
from django.db import migrations

from user_app.models import User


def create_superuser(apps, schema_editor):
    logger = logging.getLogger('django.security')
    if User.objects.has_superuser():
        logger.info("Superadmin already exists! Skipping account creation!")
    else:
        params = dict(
            email='admin@example.com',
            display_name='Admin',
            password=User.objects.make_random_password(length=32),
        )

        logger.info(f"Creating Superadmin account: {params}")
        User.objects.create_superuser(**params)
    
    
class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_auto_20200207_0857'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
