# Generated by Django 3.0 on 2020-01-14 01:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('course_app', '0005_auto_20200113_0402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=32, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.Lesson')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
