# Generated by Django 3.0 on 2020-01-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0006_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='activity',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
