# Generated by Django 3.0 on 2020-01-14 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0008_auto_20200114_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='icon',
        ),
    ]
