# Generated by Django 3.0 on 2020-01-14 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('course_app', '0009_remove_activity_icon'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('content_type', 'object_id')},
        ),
    ]
