# Generated by Django 3.0 on 2020-01-14 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0010_auto_20200114_0426'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='activity',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='object_id',
        ),
    ]
