# Generated by Django 3.0 on 2020-01-14 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('course_app', '0011_auto_20200114_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_course_app.activity_set+', to='contenttypes.ContentType'),
        ),
    ]
