# Generated by Django 3.0 on 2020-01-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0012_activity_polymorphic_ctype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
