# Generated by Django 3.0 on 2020-01-17 03:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_app', '0014_solution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='solution',
            unique_together={('activity_id', 'user_id')},
        ),
    ]
