# Generated by Django 3.0 on 2020-01-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0015_auto_20200117_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
