# Generated by Django 3.0 on 2020-01-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0016_activity_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='score',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
