# Generated by Django 3.0 on 2020-02-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0019_solution_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
