# Generated by Django 3.0 on 2020-02-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0020_activity_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='enabled',
            field=models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], default=False),
        ),
    ]
