# Generated by Django 3.0 on 2020-01-23 00:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    replaces = [('help_app', '0001_initial'), ('help_app', '0003_auto_20191215_2147'), ('help_app', '0004_auto_20191215_2202'), ('help_app', '0005_auto_20191215_2210'), ('help_app', '0006_remove_article_parent'), ('help_app', '0007_auto_20200109_2241'), ('help_app', '0008_auto_20200122_2348')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=1000)),
            ],
        ),
    ]
