# Generated by Django 3.0 on 2019-12-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
