# Generated by Django 3.0 on 2020-02-07 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help_app', '0002_auto_20200207_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('order',)},
        ),
    ]
