# Generated by Django 3.0 on 2019-12-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_app', '0004_auto_20191215_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
