# Generated by Django 3.0 on 2019-12-15 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help_app', '0005_auto_20191215_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='parent',
        ),
    ]
