# Generated by Django 3.0 on 2020-01-22 23:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('help_app', '0007_auto_20200109_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
